spring:
  application:
    name: easymonitor

  datasource:
    url: dbc:sqlserver://pluris-rds-sql-01.c9mn1wtcodo7.sa-east-1.rds.amazonaws.com:1433;databaseName=EASYTI;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: easyti
    password: dg@ht0ert59

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true

  h2:
    console:
      enabled: false
      path: /h2-console

  rabbitmq:
    addresses: amqp://Pluris:pluris12345@192.168.0.91:5672
