spring:
  application:
    name: Sentinels

  datasource:
    url: dbc:sqlserver://DATABASE:PORT;databaseName=DATABASE;encrypt=true;trustServerCertificate=true;
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: USER
    password: PASSWORD

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true

  h2:
    console:
      enabled: false
      path: /h2-console

  rabbitmq:
    addresses: amqp://RMQ:RMQ@127.0.0.1:5672
